# Generated by Django 3.1.4 on 2020-12-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_chain',
            field=models.CharField(max_length=64, verbose_name='Название сети'),
        ),
    ]
