# Generated by Django 3.1.4 on 2020-12-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201229_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_location_latitude',
            field=models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Координаты ресторана, широта'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_location_longitude',
            field=models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Координаты ресторана, долгота'),
        ),
    ]
