# Generated by Django 3.1.4 on 2020-12-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201229_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_name',
            new_name='restaurant_id',
        ),
    ]
